### ISSUE TITLE
DropboxServerException (nginx): 500 Internal Server Error (Internal Server Error)

### ISSUE THREAD

**Issue by Harin-Kaklotar** [mlamina/DropboxSDK-for-Android#2]
Hi i use this library for access dropbox in my application. in my application i need download data from dropbox in my application,i have code for it. 
everything is ok  selected file is created in sdcard bit it not download it give some error

error:
11-30 10:10:50.971: W/EGL_emulation(3110): eglSurfaceAttrib not implemented
11-30 10:10:50.971: W/OpenGLRenderer(3110): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa487cf40, error=EGL_SUCCESS
11-30 10:10:53.295: W/System.err(3110): DropboxServerException (nginx): 500 Internal Server Error (Internal Server Error)
11-30 10:10:53.295: W/System.err(3110):     at com.dropbox.client2.RESTUtility.parseAsJSON(RESTUtility.java:265)
11-30 10:10:53.295: W/System.err(3110):     at com.dropbox.client2.RESTUtility.execute(RESTUtility.java:415)
11-30 10:10:53.295: W/System.err(3110):     at com.dropbox.client2.RESTUtility.execute(RESTUtility.java:339)
11-30 10:10:53.295: W/System.err(3110):     at com.dropbox.client2.DropboxAPI.getFileStream(DropboxAPI.java:1549)
11-30 10:10:53.296: W/System.err(3110):     at yptech.privategallery.upload1.DropboxDownload$3.run(DropboxDownload.java:292)
11-30 10:10:53.296: W/System.err(3110):     at java.lang.Thread.run(Thread.java:818)

I got error in this method

---

 private void copy(final Entry fileSelected, final File localFile) {
        final ProgressDialog pd = ProgressDialog.show(DropboxDownload.this, "Downloading...","Please wait...");

```
    new Thread(new Runnable() {

        @Override
        public void run() {
            BufferedInputStream br = null;
            BufferedOutputStream bw = null;
            DropboxInputStream fd;
            try {
                fd = mApi.getFileStream(fileSelected.path,localFile.getPath());//****Here I get error******
                br = new BufferedInputStream(fd);
                bw = new BufferedOutputStream(new FileOutputStream( localFile));
                byte[] buffer = new byte[4096];
                int read;
                while (true) {
                    read = br.read(buffer);
                    if (read <= 0) {
                        break;
                    }
                    bw.write(buffer, 0, read);
                }
                pd.dismiss();
                Message message = new Message();
                message.obj = localFile.getAbsolutePath();
                message.what = 1;
                mHandler.sendMessage(message);
            } catch (DropboxException e) {
                e.printStackTrace();
            } catch (FileNotFoundException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                if (bw != null) {
                    try {
                        bw.close();
                        if (br != null) {
                            br.close();
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }).start();
}
```

---

**Comment by Harin-Kaklotar** [comment]
Hi I change the dropbox sdk version in my project and my problem is solve

**Comment by mlamina** [comment]
Sorry for my late response...
This project is very old and the Dropbox SDK has come a long way since I've started this! 
I suggest you take a look at the official SDK: https://www.dropbox.com/developers-v1/core/sdks/android
